[package]
name = "mem_cleaner"
version = "0.1.1"
edition = "2025"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
dialoguer = "0.11"
